### ISSUE TITLE
Rotate and Translate Img and Text

### ISSUE THREAD

**Issue by eudorias** [jeromeetienne/threex.dynamictexture#5]
How can i achive this with threex.dynamictexture without broke texture coordinates.

**Comment by jeromeetienne** [comment]
just draw on the 2d canvas the drawing you like. you dont need to know about specific texture coordinates

the context is available in `dynamicTexture.context`, dont forget to do `dynamicTexture.texture.needsUpdate = true` when you are done drawing, this will update the texture on the gpu and make it appears on screen
